name: CD

on:
  push:
    branches:
      - 'main'

  schedule:
    - cron: '0 13 * * 1' # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
    

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PAGES_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}

    steps:
      - name: Trigger Cloudflare Pages build
        if: startsWith(env.CLOUDFLARE_PAGES_DEPLOY_HOOK, 'https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}


      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

              # Initiate deployment status
      # - name: Start Deployment
      #   uses: bobheadxi/deployments@v1.4.0
      #   id: deployment
      #   with:
      #     step: start
      #     env: Preview

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Hugo
        env: # Or as an environment variable
         NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
         BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN}}
         
        run: |
          npm install
          npm install --cpu=x64 --os=linux sharp
          npm start
          hugo

      # - name: Commit updated content
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Sync content with Notion

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

         # Step 4 - Push our generated site to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
          github-comment: false
          vercel-args: '--prod' #Optional
          working-directory: public

      #   # Update deployment status
      # - name: Update Deployment Status
      #   uses: bobheadxi/deployments@v1.4.0
      #   if: always()
      #   with:
      #     step: finish
      #     status: ${{ job.status }}
      #     deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      #     env_url: ${{ steps.vercel-action.outputs.preview-url }}


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
